import os

# * API KEYS
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')
OPENAI_API_KEY = os.environ['OPENAI_API_KEY']
OPENAI_ORGANIZATION_ID = os.environ['OPENAI_ORGANIZATION_ID']

# * SECRETS
PROMPT_TEMPLATES_PATH = os.environ['PROMPT_TEMPLATES_PATH']

# * SETUP
ALLOWED_ORIGINS = os.environ['ALLOWED_ORIGINS'].split(';')
VALID_API_KEYS_MAPPING_PATH = os.environ['VALID_API_KEYS_MAPPING_PATH']

# * CELERY
CELERY_BROKER_URL = os.environ['CELERY_BROKER_URL']